// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecallOps.Api.Data;

#nullable disable

namespace RecallOps.Api.Data.Migrations
{
    [DbContext(typeof(RecallOpsDbContext))]
    partial class RecallOpsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecallOps.Api.Models.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IncidentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean");

                    b.Property<string>("Logs")
                        .HasColumnType("text");

                    b.Property<string>("RecentChanges")
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RootCause")
                        .HasColumnType("text");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symptoms")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Service");

                    b.HasIndex("Status");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("RecallOps.Api.Models.IncidentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentEvents");
                });

            modelBuilder.Entity("RecallOps.Api.Models.IncidentFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("LessonsLearned")
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<string>("RootCause")
                        .HasColumnType("text");

                    b.Property<string>("WhatFailed")
                        .HasColumnType("text");

                    b.Property<string>("WhatWorked")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentFeedbacks");
                });

            modelBuilder.Entity("RecallOps.Api.Models.ServiceInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13fffe69-0d8e-44c8-a237-3c8681583c8b"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Payment API production service",
                            Name = "Payment API",
                            Owner = "SRE Team"
                        },
                        new
                        {
                            Id = new Guid("6736f8cc-070a-4548-9d7c-99bc58f838ae"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication API production service",
                            Name = "Authentication API",
                            Owner = "SRE Team"
                        },
                        new
                        {
                            Id = new Guid("33fd9c1a-5eb1-4d57-a549-4abe39e2d5ea"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Order Service production service",
                            Name = "Order Service",
                            Owner = "SRE Team"
                        },
                        new
                        {
                            Id = new Guid("661d2385-fe06-42c3-bb81-0584256e0ba7"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Notification Service production service",
                            Name = "Notification Service",
                            Owner = "SRE Team"
                        },
                        new
                        {
                            Id = new Guid("a7a19fbf-d508-4903-bce1-114284db05c7"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "User API production service",
                            Name = "User API",
                            Owner = "SRE Team"
                        },
                        new
                        {
                            Id = new Guid("1982fcc4-5bcb-4bcc-b53e-772265942c97"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Search Service production service",
                            Name = "Search Service",
                            Owner = "SRE Team"
                        },
                        new
                        {
                            Id = new Guid("9915d5bf-e41a-48ce-98ed-63fe8e6b5a3e"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "API Gateway production service",
                            Name = "API Gateway",
                            Owner = "SRE Team"
                        },
                        new
                        {
                            Id = new Guid("1071488b-beb5-4958-a719-9ec1bd57eef9"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Redis Cache production service",
                            Name = "Redis Cache",
                            Owner = "SRE Team"
                        },
                        new
                        {
                            Id = new Guid("8cd9a3d5-a5a2-43cd-8ca2-dd856a084df4"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "PostgreSQL Database production service",
                            Name = "PostgreSQL Database",
                            Owner = "SRE Team"
                        },
                        new
                        {
                            Id = new Guid("c8043c74-bfea-4b5f-80ec-3d6072344239"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "File Storage Service production service",
                            Name = "File Storage Service",
                            Owner = "SRE Team"
                        });
                });

            modelBuilder.Entity("RecallOps.Api.Models.IncidentEvent", b =>
                {
                    b.HasOne("RecallOps.Api.Models.Incident", "Incident")
                        .WithMany("Events")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("RecallOps.Api.Models.IncidentFeedback", b =>
                {
                    b.HasOne("RecallOps.Api.Models.Incident", "Incident")
                        .WithMany("Feedbacks")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("RecallOps.Api.Models.Incident", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Feedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
